repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.0"
    hooks:
      - id: ruff
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.18.1"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: ["types-requests", "types-PyYAML"]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: ["-d", "{extends: relaxed, rules: {line-length: disable}}"]

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.7.3
    hooks:
      - id: pydoclint
        args: [--style=numpy, --check-return-types=False]
