"""salt.core — modular v2 core.

Re-exports the graph-kernel public API, the dataset schema artifact API,
and the Lightning integration (`SaltModule`). Dataset/model modules live
in `salt.core.data` / `salt.core.nn`; the ``salt2`` CLI lives in
`salt.core.main` and is not re-exported here.
"""

from __future__ import annotations

from salt.core.graph import (
    IO,
    KEY_SEP,
    KINDS,
    PRIMARY_MODES,
    SINKS,
    SOURCES,
    AllModesDeadError,
    Bundle,
    ConfigError,
    ConnectivityError,
    CycleError,
    DeadOutput,
    DeclarationError,
    Edge,
    GraphError,
    GraphModule,
    KeyCollisionError,
    Kind,
    KindError,
    Mode,
    MutationError,
    NestedSpec,
    Plan,
    PlanStep,
    SchemaError,
    ShapeError,
    Sinks,
    TensorSpec,
    check_key_component,
    compile_plan,
    deadcode,
    flatten_spec,
    is_symbolic_dim,
    iter_spec_leaves,
    join_key,
    split_key,
    split_symbolic_dim,
    sym_dim,
    unflatten_spec,
)
from salt.core.saltmodule import CKPT_KEY, SaltModule, bundle_as_v1_outputs
from salt.core.schema import (
    SCHEMA_VERSION,
    GroupSchema,
    KeyValidation,
    Schema,
    dump_schema,
    load_schema,
    save_schema,
)

__all__ = [
    "CKPT_KEY",
    "IO",
    "KEY_SEP",
    "KINDS",
    "PRIMARY_MODES",
    "SCHEMA_VERSION",
    "SINKS",
    "SOURCES",
    "AllModesDeadError",
    "Bundle",
    "ConfigError",
    "ConnectivityError",
    "CycleError",
    "DeadOutput",
    "DeclarationError",
    "Edge",
    "GraphError",
    "GraphModule",
    "GroupSchema",
    "KeyCollisionError",
    "KeyValidation",
    "Kind",
    "KindError",
    "Mode",
    "MutationError",
    "NestedSpec",
    "Plan",
    "PlanStep",
    "SaltModule",
    "Schema",
    "SchemaError",
    "ShapeError",
    "Sinks",
    "TensorSpec",
    "bundle_as_v1_outputs",
    "check_key_component",
    "compile_plan",
    "deadcode",
    "dump_schema",
    "flatten_spec",
    "is_symbolic_dim",
    "iter_spec_leaves",
    "join_key",
    "load_schema",
    "save_schema",
    "split_key",
    "split_symbolic_dim",
    "sym_dim",
    "unflatten_spec",
]
