"""Driver: run upstream-6570e85 MaskFormer fit+test to produce a TEST H5 with the objects group.

PROVENANCE of this fixture directory (MFU-0 step C, captured 2026-06-28)
=======================================================================
Produces ``upstream_6570e85_mf_test.h5`` (the writer-parity reference) and
``upstream_6570e85_schema.json`` (its canonical, batch-agnostic schema).

The H5 is generated by the FAITHFUL upstream prediction-writing path:
``salt.callbacks.predictionwriter.PredictionWriter`` (write_tracks=True,
write_objects=True) at upstream commit
6570e85881a395bbbd27db673f0be2c4b57e1898, driven by ``salt/configs/MaskFormer.yaml``
on the standard dummy inputs (``salt.utils.inputs.write_dummy_file`` /
``write_dummy_norm_dict``). This mirrors run_train / run_eval from
salt/tests/test_pipeline.py (no onnx, no muP).

EXACT command used (run from the upstream-6570e85 scratch worktree):

    # 1. create a scratch worktree pinned to the upstream commit
    git -C repos/salt/salt worktree add -b mfu0-upstream-6570e85 \\
        ../worktrees/upstream-6570e85 6570e85

    # 2. inside the salt-py314 container (rebuilt WITH py_lap_solver):
    SIF=tools/containers/images/salt-py314.sif
    WT=repos/salt/worktrees/upstream-6570e85
    apptainer exec --nv --bind $WT --bind /tmp --bind <scratch> $SIF bash -c \\
      "cd $WT && pip install --no-deps -e . && \\
       pip install --user --no-deps seaborn scikit-learn && \\
       python regenerate_upstream_fixture.py <OUT_ROOT>"

The 16-jet H5 fixture is then a gzip-recompressed 16-row subset of the
1000-jet test output (subset_h5.py / make_canonical.py in the same MFU-0 run).

NOTE (does NOT affect schema): py-lap-solver 0.1.4 in this container exposes
only Scipy/ScipyMP8, not the OpenMP-built BatchedScipyOMP that the upstream
matcher defaults to. The LAP solver only changes numeric matching, never the
written H5 schema, so this driver aliases BatchedScipyOMP -> Scipy in the
solver registry so the unmodified upstream writer path can run.

Models run_train / run_eval from salt/tests/test_pipeline.py (no onnx, no muP).
Writes everything under OUT_ROOT so the produced H5 survives for inspection.
"""

import sys
from pathlib import Path

import yaml

from salt.main import main
from salt.utils.inputs import write_dummy_file, write_dummy_norm_dict

# py-lap-solver 0.1.4 in this container exposes only Scipy/ScipyMP8 (the
# OpenMP-built BatchedScipyOMP default isn't compiled in). The LAP solver only
# affects numeric matching, NOT the written H5 schema, so alias the default to
# Scipy to let the faithful upstream writer path run unchanged.
from salt.models import matcher as _matcher

if "BatchedScipyOMP" not in _matcher.SOLVER_REGISTRY:
    _matcher.SOLVER_REGISTRY["BatchedScipyOMP"] = _matcher.SOLVER_REGISTRY["Scipy"]

OUT_ROOT = Path(sys.argv[1])
OUT_ROOT.mkdir(parents=True, exist_ok=True)

config_path = Path("salt/configs/MaskFormer.yaml").resolve()

# ---- fit ----
sys.argv = [sys.argv[0]]  # clear so the salt CLI doesn't see our args
train_h5 = OUT_ROOT / "dummy_train_inputs.h5"
nd_path = OUT_ROOT / "dummy_norm_dict.yaml"
cd_path = OUT_ROOT / "dummy_class_dict.yaml"
write_dummy_norm_dict(nd_path, cd_path)
write_dummy_file(train_h5, nd_path)

fit_args = [
    "fit",
    f"--config={config_path}",
    f"--data.norm_dict={nd_path}",
    f"--data.class_dict={cd_path}",
    f"--data.train_file={train_h5}",
    f"--data.val_file={train_h5}",
    "--data.num_train=500",
    "--data.num_val=100",
    "--data.batch_size=20",
    "--data.num_workers=0",
    "--trainer.max_epochs=1",
    "--trainer.accelerator=cpu",
    "--trainer.devices=1",
    f"--trainer.default_root_dir={OUT_ROOT}",
    "--trainer.logger.init_args.online=False",
]
main(fit_args)

# ---- locate train dir ----
train_dirs = [x for x in OUT_ROOT.iterdir() if x.is_dir() and (x / "config.yaml").exists()]
assert len(train_dirs) == 1, train_dirs
train_dir = train_dirs[0]
train_config_path = train_dir / "config.yaml"
nd = [x for x in train_dir.iterdir() if x.suffix == ".yaml" and "norm" in str(x)][0]

# ensure write_tracks True (config already has it, mirror run_eval anyway)
with open(train_config_path) as f:
    cfg = yaml.safe_load(f)
for cb in cfg["trainer"]["callbacks"]:
    if "PredictionWriter" in cb["class_path"]:
        cb["init_args"]["write_tracks"] = True
        cb["init_args"]["write_objects"] = True
with open(train_config_path, "w") as f:
    yaml.dump(cfg, f)

# ---- test ----
test_h5 = OUT_ROOT / "dummy_test_sample_inputs.h5"
write_dummy_file(test_h5, nd)
test_args = [
    "test",
    f"--config={train_config_path}",
    f"--data.test_file={test_h5}",
    "--data.num_test=1000",
    "--data.batch_size=100",
    "--trainer.accelerator=cpu",
]
main(test_args)

# ---- report produced H5 ----
ckpt_dir = train_dir / "ckpts"
h5s = [f for f in ckpt_dir.iterdir() if f.suffix == ".h5"]
print("PRODUCED_H5:", *[str(p) for p in h5s])
