# On top of GN3_Hybrid or GN3_Charge
# Adds electrons and concatenates jet features to global jet representation
name: GN3_SoftE

model:
  model:
    class_path: salt.models.SaltModel
    init_args:
      init_nets:
        - input_name: tracks
          dense_config: &init
            output_size: &embed_dim 512
            hidden_layers: [512]
            activation: &activation SiLU
        # Adding flows
        - input_name: flows
          dense_config:
            <<: *init
        # Adding electrons
        - input_name: electrons
          dense_config:
            <<: *init

      tasks:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.ClassificationTask
              init_args:
                name: jets_classification
                input_name: jets
                label: flavour_label
                use_class_dict: True
                loss: torch.nn.CrossEntropyLoss
                dense_config: &task_dense_config
                  input_size: &pooled_dim 258
                  # split light classes
                  output_size: 6
                  hidden_layers: [128, 64, 32]
                  activation: *activation
            - class_path: salt.models.ClassificationTask
              init_args:
                name: track_origin
                input_name: tracks
                label: ftagTruthOriginLabel
                use_class_dict: True
                loss: torch.nn.CrossEntropyLoss
                dense_config:
                  <<: *task_dense_config
                  input_size: &out_dim 256
                  output_size: 8
                  context_size: *pooled_dim
                  activation: *activation
            - class_path: salt.models.VertexingTask
              init_args:
                name: track_vertexing
                input_name: tracks
                label: ftagTruthVertexIndex
                loss:
                  class_path: torch.nn.BCEWithLogitsLoss
                  init_args: { reduction: none }
                dense_config:
                  <<: *task_dense_config
                  input_size: 512
                  output_size: 1
                  context_size: *pooled_dim
                  activation: *activation
            # TrackType task
            - class_path: salt.models.ClassificationTask
              init_args:
                name: track_type
                input_name: tracks
                label: ftagTruthTypeLabel
                label_map: { -2: 2, -3: 3, 5: 4, -5: 4, 6: 5, -6: 5 }
                class_names: [NoTruth, Other, Pion, Kaon, Electron, Muon]
                loss:
                  class_path: torch.nn.CrossEntropyLoss
                  init_args:
                    weight: [3.56, 13.3, 1.0, 6.49, 21.48, 109.72]
                dense_config:
                  <<: *task_dense_config
                  input_size: *out_dim
                  output_size: 6
                  context_size: *pooled_dim
                  activation: *activation
            # Jet pT regression task
            - class_path: salt.models.RegressionTask
              init_args:
                name: jet_pt_regression
                input_name: jets
                targets: ptFromTruthDressedWZJet
                target_denominators: pt_btagJes
                loss:
                  class_path: torch.nn.L1Loss
                  init_args: { reduction: none }
                dense_config:
                  <<: *task_dense_config
                  output_size: 1
                  activation: *activation

data:
  input_map:
    GLOBAL: GLOBAL
    jets: jets
    tracks: tracks_ghost
    flows: flows
    electrons: electrons
  variables:
    GLOBAL:
      - pt_btagJes
      - eta_btagJes
    jets:
      - pt_btagJes
      - eta_btagJes
    tracks:
      - d0
      - z0SinTheta
      - dphi
      - deta
      - qOverP
      - lifetimeSignedD0Significance
      - lifetimeSignedZ0SinThetaSignificance
      - phiUncertainty
      - thetaUncertainty
      - qOverPUncertainty
      - numberOfPixelHits
      - numberOfSCTHits
      - numberOfInnermostPixelLayerHits
      - numberOfNextToInnermostPixelLayerHits
      - numberOfInnermostPixelLayerSharedHits
      - numberOfInnermostPixelLayerSplitHits
      - numberOfPixelSharedHits
      - numberOfPixelSplitHits
      - numberOfSCTSharedHits
      # Soft Muon variables
      - leptonID
      - muon_quality
      - muon_qOverPratio
      - muon_momentumBalanceSignificance
      - muon_scatteringNeighbourSignificance
    flows:
      - pt
      - energy
      - deta
      - dphi
      - isCharged
    electrons:
      - pt
      - ptfrac
      - ptrel
      - dr
      - abs_eta
      - eta
      - phi
      - ftag_et
      - qOverP
      - d0RelativeToBeamspot
      - d0RelativeToBeamspotSignificance
      - ftag_ptVarCone30OverPt
      - numberOfPixelHits
      - numberOfSCTHitsInclDead
      - ftag_deltaPOverP
      - eProbabilityHT
      - deltaEta1
      - deltaPhiRescaled2
      - ftag_energyOverP
      - Rhad
      - Rhad1
      - Eratio
      - weta2
      - Rphi
      - Reta
      - wtots1
      - f1
      - f3
