name: GN3V01

model:
  # Lion GLS addition
  optimizer: lion
  loss_mode: GLS
  lrs_config:
    initial: 2e-8
    max: 1e-4
    end: 2e-6
    pct_start: 0.01
    weight_decay: 1e-5

  model:
    class_path: salt.models.SaltModel
    init_args:

      init_nets:
        - input_name: tracks
          dense_config: &init
            output_size: &embed_dim 512
            hidden_layers: [512]
            activation: &activation SiLU
        # Adding flows
        - input_name: flows
          dense_config:
            <<: *init
        # Adding electrons
        - input_name: electrons
          dense_config:
            <<: *init

      encoder:
        class_path: salt.models.TransformerV2
        init_args:
          num_layers: 4
          embed_dim: *embed_dim
          out_dim: &out_dim 256
          # flash attention
          attn_type: flash-varlen
          norm: RMSNorm
          norm_type: hybrid
          dense_kwargs:
            activation: *activation
            gated: True
          attn_kwargs:
            num_heads: 8
          num_registers: 8

      pool_net:
        class_path: salt.models.GlobalAttentionPooling
        init_args: { input_size: *out_dim }

      tasks:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.ClassificationTask
              init_args:
                name: jets_classification
                input_name: jets
                label: flavour_label
                use_class_dict: True
                loss: torch.nn.CrossEntropyLoss
                dense_config: &task_dense_config
                  input_size: *out_dim
                  # split light classes
                  output_size: 6
                  hidden_layers: [128, 64, 32]
                  activation: *activation
            - class_path: salt.models.ClassificationTask
              init_args:
                name: track_origin
                input_name: tracks
                label: ftagTruthOriginLabel
                use_class_dict: True
                loss: torch.nn.CrossEntropyLoss
                dense_config:
                  <<: *task_dense_config
                  output_size: 8
                  context_size: *out_dim
                  activation: *activation
            - class_path: salt.models.VertexingTask
              init_args:
                name: track_vertexing
                input_name: tracks
                label: ftagTruthVertexIndex
                loss:
                  class_path: torch.nn.BCEWithLogitsLoss
                  init_args: { reduction: none }
                dense_config:
                  <<: *task_dense_config
                  input_size: 512
                  output_size: 1
                  context_size: *out_dim
                  activation: *activation
            # TrackType task
            - class_path: salt.models.ClassificationTask
              init_args:
                name: track_type
                input_name: tracks
                label: ftagTruthTypeLabel
                label_map: {-2: 2, -3: 3, 5: 4, -5: 4, 6: 5, -6: 5}
                class_names: [NoTruth, Other, Pion, Kaon, Electron, Muon]
                loss:
                  class_path: torch.nn.CrossEntropyLoss
                  init_args:
                    weight: [3.5, 13.34, 1.0, 6.47, 21.5, 112.1]
                dense_config:
                  <<: *task_dense_config
                  output_size: 6
                  context_size: *out_dim
                  activation: *activation
            # Jet pT regression task
            - class_path: salt.models.RegressionTask
              init_args:
                name: jet_pt_regression
                input_name: jets
                targets: ptFromTruthDressedWZJet
                target_denominators: pt_btagJes
                loss:
                  class_path: torch.nn.L1Loss
                  init_args: { reduction: none }
                dense_config:
                  <<: *task_dense_config
                  output_size: 1
                  activation: *activation
             # B-jet charge classification task
            - class_path: salt.models.ClassificationTask
              init_args:
                name: jets_charge
                input_name: jets
                label: HadronGhostInitialTruthLabelPdgId
                label_map: {0: 2, 15: 2, -15: 2, 511: 1, -511: 0, 513: 1, -513: 0, 521: 1, -521: 0, 523: 1, -523: 0, 10511: 1, -10511: 0, 531: 1, -531: 0, 541: 1, -541: 0, 543: 1, -543: 0, 10551: 0, 100551: 0, 110551: 1, 20553: 1, 100553: 0, 100555: 1, 200553: 0, 120553: 1, 551: 0, 553: 1, 555: 0, 431: 2, -431: 2, 421: 2, -421: 2, 411: 2, -411: 2, 441: 2, 443: 2, 445: 2, 4122: 2, -4122: 2, 4132: 2, -4132: 2, 4114: 2, -4114: 2, 4232: 2, -4232: 2, 4332: 2, -4332: 2, 10441: 2, 10443: 2, 20443: 2, 100441: 2, 100443: 2, 30443: 2, 5122: 0, -5122: 1, 5132: 0, -5132: 1, 5232: 0, -5232: 1, 5332: 0, -5332: 1, 4412: 2, 4422: 2, -4412: 2, -4422: 2, 4414: 2, 4424: 2, -4414: 2, -4424: 2, 4432: 2, -4432: 2, 4434: 2, -4434: 2, 4444: 2, -4444: 2, -4322: 2, 4322: 2, 5142: 0, 5242: 0, -5142: 1, -5242: 1, 5412: 0, 5422: 0, -5412: 1, -5422: 1, 5414: 0, 5424: 0, -5414: 1, -5424: 1, 5342: 0, -5342: 1, 5432: 0, -5432: 1, 5434: 0, -5434: 1, 5442: 0, -5442: 1, 5444: 0, -5444: 1, 5512: 0, -5512: 1, 5522: 0, -5522: 1, 5514: 0, -5514: 1, 5532: 0, -5532: 1, 5534: 0, -5534: 1, 5542: 0, -5542: 1, 5544: 0, -5544: 1, 5554: 0, -5554: 1, 20433: 2, -20433: 2, 10431: 2, -10431: 2, 4334: 2, -4334: 2, 4324: 2, -4324: 2, 4314: 2, -4314: 2, 4312: 2, -4312: 2, 4224: 2, -4224: 2, 4222: 2, -4222: 2, 4214: 2, -4214: 2, 4212: 2, -4212: 2, 4112: 2, -4112: 2, 433: 2, -433: 2, 425: 2, -425: 2, 423: 2, -423: 2, 413: 2, -413: 2, 14122: 2, -14122: 2, 10433: 2, -10433: 2, 10423: 2, -10423: 2, 10421: 2, -10421: 2, 10413: 2, -10413: 2, 10411: 2, -10411: 2, 4124: 2, -4124: 2, 20413: 2, -20413: 2, 20423: 2, -20423: 2, 9010443: 2, 435: 2, -435: 2, 415: 2, -415: 2, -5334: 1, 5334: 0, 5324: 0, -5324: 1, 5322: 0, -5322: 1, 5314: 0, -5314: 1, 5312: 0, -5312: 1, 5224: 0, -5224: 1, 5222: 0, -5222: 1, 5214: 0, -5214: 1, 5212: 0, -5212: 1, 5114: 0, -5114: 1, 5112: 0, -5112: 1, 533: 1, -533: 0}
                class_names: [bquark, anti-bquark, other]
                weight: 1
                loss:
                  class_path: torch.nn.CrossEntropyLoss
                  init_args:
                    weight: [20, 20, 1.0]
                dense_config:
                  <<: *task_dense_config
                  output_size: 3
                  input_size: *out_dim

data:
  input_map:
    jets: jets
    tracks: tracks_ghost
    flows: flows
    electrons: electrons
  # loose tracks
  selections: null
  non_finite_to_num: True
  variables:
    jets:
      - pt_btagJes
      - eta_btagJes
    tracks:
      - d0
      - z0SinTheta
      - dphi
      - deta
      - qOverP
      - IP3D_signed_d0_significance
      - IP3D_signed_z0_significance
      - phiUncertainty
      - thetaUncertainty
      - qOverPUncertainty
      - numberOfPixelHits
      - numberOfSCTHits
      - numberOfInnermostPixelLayerHits
      - numberOfNextToInnermostPixelLayerHits
      - numberOfInnermostPixelLayerSharedHits
      - numberOfInnermostPixelLayerSplitHits
      - numberOfPixelSharedHits
      - numberOfPixelSplitHits
      - numberOfSCTSharedHits
      # Soft Muon variables
      - leptonID
      - muon_quality
      - muon_qOverPratio
      - muon_momentumBalanceSignificance
      - muon_scatteringNeighbourSignificance
    flows:
      - pt
      - energy
      - deta
      - dphi
      - isCharged
    electrons:
      - pt
      - ptfrac
      - ptrel
      - dr
      - abs_eta
      - eta
      - phi
      - ftag_et
      - qOverP
      - d0RelativeToBeamspot
      - d0RelativeToBeamspotSignificance
      - ftag_ptVarCone30OverPt
      - numberOfPixelHits
      - numberOfSCTHitsInclDead
      - ftag_deltaPOverP
      - eProbabilityHT
      - deltaEta1
      - deltaPhiRescaled2
      - ftag_energyOverP
      - Rhad
      - Rhad1
      - Eratio
      - weta2
      - Rphi
      - Reta
      - wtots1
      - f1
      - f3

  train_file: /share/lustre/wlai/datasets/atlas/gn3v00/ghost_high_stat_full/output/pp_output_train.h5
  val_file: /share/lustre/wlai/datasets/atlas/gn3v00/ghost_high_stat_full/output/pp_output_val.h5
  norm_dict: /share/lustre/wlai/datasets/atlas/gn3v00/ghost_high_stat_full/output/norm_dict.yaml
  class_dict: /share/lustre/wlai/datasets/atlas/gn3v00/ghost_high_stat_full/output/class_dict.yaml

  batch_size: 4000
  num_workers: 20

trainer:
  max_epochs: 40
  accelerator: gpu
  devices: 1
  precision: bf16-mixed
