variables:
  MKDOCS_VERSION: '1.2.3'
  MATERIAL_VERSION: '8.2.7'

pages:
  image: python:3.9.14
  stage: docs
  script:
    - pip install mkdocs==${MKDOCS_VERSION} mkdocs-material==${MATERIAL_VERSION}
    - mkdocs build -d public
    - if [[ -f _redirects ]]; then cp _redirects public; fi;
  artifacts:
    paths:
    - public
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_PATH=="atlas-flavor-tagging-tools/algorithms/salt"
      when: always
