pages:
  image: registry.cern.ch/docker.io/library/python:3.11.2
  stage: docs
  needs: []
  before_script:
    - pip install -r docs/requirements.txt
  script:
    - indicomb2 --config docs/indicomb.yaml
    - mkdocs build -s -d public
    - if [[ -f _redirects ]]; then cp _redirects public; fi;
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  variables:
    GIT_DEPTH: 0
    GIT_STRATEGY: clone
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_PATH=="aft/algorithms/salt"
      when: always
