pre-commit:
  stage: lint
  needs: []
  image: registry.cern.ch/docker.io/library/python:3.11.2
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success
  script:
    - python -m pip install uv
    - uv sync --only-group dev
    - uv run --no-sync pre-commit run --all-files
