variables:
  TEST_CMD: coverage run -p --source salt -m pytest --show-capture=stdout

.test-template: &test-template
  stage: tests
  needs: [build_docker_test]
  image: "$CI_REGISTRY_IMAGE/temporary_images:${CI_COMMIT_REF_SLUG}-test"
  artifacts:
    paths: [.coverage*]
  rules:
    - changes: ["pyproject.toml", "requirements.txt", "salt/**/*.py", "**/*.yaml"]

# --------------------------- UNIT TESTS ---------------------------
unit-tests:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_models.py
    - $TEST_CMD salt/tests/test_union_find.py
    - $TEST_CMD salt/tests/test_edges.py
    - $TEST_CMD salt/tests/test_utils.py
    - $TEST_CMD salt/tests/test_posenc.py
    - $TEST_CMD salt/tests/test_initnet.py
    - $TEST_CMD salt/tests/test_transformerv2.py
    - $TEST_CMD salt/tests/test_masks.py
    - $TEST_CMD salt/tests/test_featurewise.py
    - $TEST_CMD salt/tests/test_datasets.py

# --------------------------- PIPELINE TESTS ---------------------------
test-dev:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_train_dev
    - $TEST_CMD salt/tests/test_pipeline.py::test_train_movefilestemp

test-truncate-inputs:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_truncate_inputs
    - $TEST_CMD salt/tests/test_pipeline.py::test_truncate_inputs_error

test-GN1:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_GN1
    - $TEST_CMD salt/tests/test_pipeline.py::test_GN1_GATv2

test-GN2:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_GN2

test-GN3:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_GN3

test-GN2_muP:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_GN2_muP

test-GN2emu:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_GN2emu

test-GN2XE:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_GN2XE

test-DIPS-DL1:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_DIPS
    - $TEST_CMD salt/tests/test_pipeline.py::test_DL1

test-regression:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_regression
    - $TEST_CMD salt/tests/test_pipeline.py::test_nan_regression
    - $TEST_CMD salt/tests/test_pipeline.py::test_regression_gaussian

test-flow:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_flow

test-tfv2:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_tfv2

test-maskformer:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_maskformer

test-parameterisation:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_param_concat
    - $TEST_CMD salt/tests/test_pipeline.py::test_param_featurewise

test-misc:
  <<: *test-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::test_gls_weighting
    - $TEST_CMD salt/tests/test_pipeline.py::test_no_global_inputs
