.test-template:
  stage: tests
  needs: [build_docker_test]
  image: "$CI_REGISTRY_IMAGE/temporary_images:${CI_COMMIT_REF_SLUG}-test"
  artifacts:
    when: always
    paths:
      - .coverage*
      - reports/
    reports:
      junit: reports/*.xml
  before_script:
    - |
      run_test() {
        coverage run -p --source salt -m pytest --show-capture=stdout --junitxml="${JUNIT_FILE:-report.xml}" "$@"
      }
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success

# --------------------------- UNIT TESTS ---------------------------
unit-tests:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/unit-models.xml run_test salt/tests/test_models.py
    - JUNIT_FILE=reports/unit-union_find.xml run_test salt/tests/test_union_find.py
    - JUNIT_FILE=reports/unit-edges.xml run_test salt/tests/test_edges.py
    - JUNIT_FILE=reports/unit-utils.xml run_test salt/tests/test_utils.py
    - JUNIT_FILE=reports/unit-posenc.xml run_test salt/tests/test_posenc.py
    - JUNIT_FILE=reports/unit-initnet.xml run_test salt/tests/test_initnet.py
    - JUNIT_FILE=reports/unit-transformerv2.xml run_test salt/tests/test_transformerv2.py
    - JUNIT_FILE=reports/unit-masks.xml run_test salt/tests/test_masks.py
    - JUNIT_FILE=reports/unit-featurewise.xml run_test salt/tests/test_featurewise.py
    - JUNIT_FILE=reports/unit-datasets.xml run_test salt/tests/test_datasets.py

# --------------------------- PIPELINE TESTS ---------------------------
test-dev:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/dev.xml run_test salt/tests/test_pipeline.py::test_train_dev
    - JUNIT_FILE=reports/dev-move.xml run_test salt/tests/test_pipeline.py::test_train_movefilestemp

test-truncate-inputs:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/truncate.xml run_test salt/tests/test_pipeline.py::test_truncate_inputs
    - JUNIT_FILE=reports/truncate-error.xml run_test salt/tests/test_pipeline.py::test_truncate_inputs_error

test-GN1:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/gn1.xml run_test salt/tests/test_pipeline.py::test_GN1
    - JUNIT_FILE=reports/gn1-gatv2.xml run_test salt/tests/test_pipeline.py::test_GN1_GATv2

test-GN2:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/gn2.xml run_test salt/tests/test_pipeline.py::test_GN2

test-GN3:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/gn3.xml run_test salt/tests/test_pipeline.py::test_GN3

test-GN2_muP:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/gn2-mup.xml run_test salt/tests/test_pipeline.py::test_GN2_muP

test-GN2emu:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/gn2emu.xml run_test salt/tests/test_pipeline.py::test_GN2emu

test-GN2XE:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/gn2xe.xml run_test salt/tests/test_pipeline.py::test_GN2XE

test-DIPS-DL1:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/dips.xml run_test salt/tests/test_pipeline.py::test_DIPS
    - JUNIT_FILE=reports/dl1.xml run_test salt/tests/test_pipeline.py::test_DL1

test-regression:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/regression.xml run_test salt/tests/test_pipeline.py::test_regression
    - JUNIT_FILE=reports/regression-nan.xml run_test salt/tests/test_pipeline.py::test_nan_regression
    - JUNIT_FILE=reports/regression-gauss.xml run_test salt/tests/test_pipeline.py::test_regression_gaussian

test-flow:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/flow.xml run_test salt/tests/test_pipeline.py::test_flow

test-tfv2:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/tfv2.xml run_test salt/tests/test_pipeline.py::test_tfv2

test-maskformer:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/maskformer.xml run_test salt/tests/test_pipeline.py::test_maskformer

test-parameterisation:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/param-concat.xml run_test salt/tests/test_pipeline.py::test_param_concat
    - JUNIT_FILE=reports/param-featurewise.xml run_test salt/tests/test_pipeline.py::test_param_featurewise

test-misc:
  extends: .test-template
  script:
    - JUNIT_FILE=reports/misc-gls.xml run_test salt/tests/test_pipeline.py::test_gls_weighting
    - JUNIT_FILE=reports/misc-noglobal.xml run_test salt/tests/test_pipeline.py::test_no_global_inputs
