pages:
  image: python:3.11.2
  stage: docs
  needs: []
  script:
    - pip install -r docs/requirements.txt
    - mkdocs build -s -d public
    - if [[ -f _redirects ]]; then cp _redirects public; fi;
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  variables:
    GIT_DEPTH: 0
    GIT_STRATEGY: clone
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_PATH=="atlas-flavor-tagging-tools/algorithms/salt"
      when: always
