pre-commit:
  stage: lint
  needs: []
  image: registry.cern.ch/docker.io/library/python:3.11.2
  script:
    - pip install pre-commit
    - pre-commit run --all-files

label-bot:
  stage: lint
  image: registry.cern.ch/docker.io/library/python:3.11.2
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE != "merge_train"'
  variables:
    GITLAB_API_TOKEN: $BOT_TOKEN
  before_script:
    - python -m pip install --upgrade pip setuptools wheel
    - python -m pip install "python-gitlab>=4.4,<5" pyyaml
  script:
    - python .gitlab/workflow/label_bot.py
