"""`SinkAdapter` — the generated bridge driving one `RuntimeSink` from Lightning."""

from __future__ import annotations

from typing import Any

from lightning import Callback, LightningModule, Trainer

from salt.graph.bundle import Bundle
from salt.graph.errors import ConfigError
from salt.outputs.sinks.registry import register_sink
from salt.outputs.sinks.sink import RuntimeSink, SinkContext

__all__ = ["SinkAdapter", "attach_runtime_sink"]


class SinkAdapter(Callback):
    """Drives one `RuntimeSink` through the Lightning test loop.

    One adapter per sink (failure isolation, and the ordering Lightning
    already gives callbacks). The adapter is generated by the driver — a
    sink author never writes one, and never writes a Lightning hook: the
    hooks here forward to the sink's own named lifecycle.

    Closing the sink is the load-bearing part, and it takes TWO hooks.
    Lightning calls ``teardown`` when a run ends normally, but an exception
    raised inside the test loop skips it — the only hook that fires there is
    ``on_exception``. Both are wired to ``close_if_open`` (idempotent by
    contract), so a crashed test releases the sink's file handle whichever
    way the run ends.

    Parameters
    ----------
    sink : RuntimeSink
        The sink to drive.
    """

    def __init__(self, sink: RuntimeSink) -> None:
        super().__init__()
        self.sink = sink

    @property
    def state_key(self) -> str:
        """Per-sink state key, so two adapters are never conflated by Lightning."""
        return f"SinkAdapter[{getattr(self.sink, 'name', type(self.sink).__name__)}]"

    def setup(self, trainer: Trainer, pl_module: LightningModule, stage: str) -> None:
        """Enforce single-device TEST; raises `ConfigError` otherwise (multi-device
        out of scope).
        """
        del pl_module
        if stage == "test" and trainer.world_size != 1:
            raise ConfigError(
                f"{type(self.sink).__name__} requires a single device, got "
                f"world_size={trainer.world_size} — multi-device test writing is out of scope"
            )

    def on_test_start(self, trainer: Trainer, pl_module: LightningModule) -> None:
        """Open the sink schema before the first batch, from a context built off the trainer."""
        del pl_module
        self.sink.open_schema(SinkContext.from_trainer(trainer))

    def on_test_batch_end(
        self,
        trainer: Trainer,
        pl_module: LightningModule,
        outputs: Bundle,
        batch: Any,
        batch_idx: int,
        dataloader_idx: int = 0,
    ) -> None:
        """Consume one batch's executed bundle (Lightning threads the ``test_step`` return)."""
        del trainer, pl_module, batch, batch_idx, dataloader_idx
        self.sink.consume(outputs)

    def on_test_end(self, trainer: Trainer, pl_module: LightningModule) -> None:
        """Finalise the sink at test end."""
        del trainer, pl_module
        self.sink.flush()

    def teardown(self, trainer: Trainer, pl_module: LightningModule, stage: str) -> None:
        """Idempotent cleanup on the normal exit path."""
        del trainer, pl_module, stage
        self.sink.close_if_open()

    def on_exception(
        self, trainer: Trainer, pl_module: LightningModule, exception: BaseException
    ) -> None:
        """Idempotent cleanup on the CRASH path — `teardown` does not run there.

        A raise inside the test loop unwinds past `on_test_end`/`teardown`;
        ``on_exception`` is the only hook Lightning still calls, so this is
        what actually keeps a half-written H5 from leaking its handle.
        """
        del trainer, pl_module, exception
        self.sink.close_if_open()


def attach_runtime_sink(trainer: Any, sink: Any) -> SinkAdapter | None:
    """Register `sink` on `trainer` and, for a runtime sink, generate its adapter.

    The one wiring entry point: every path that adds a sink to a run (a
    command's implicit injection and the ``outputs:`` section) goes through
    here, so discovery and the Lightning bridge can never disagree. A
    declare-only `Node` (the ONNX manifest) is registered but gets no
    adapter — it has no lifecycle to drive.

    Parameters
    ----------
    trainer : Any
        The trainer to wire the sink into. None registers nothing.
    sink : Any
        The sink node.

    Returns
    -------
    SinkAdapter | None
        The generated adapter, appended to ``trainer.callbacks``, or None for
        a declare-only node.
    """
    if trainer is None:
        return None
    register_sink(trainer, sink)
    if not isinstance(sink, RuntimeSink):
        return None
    adapter = SinkAdapter(sink)
    callbacks = getattr(trainer, "callbacks", None)
    if callbacks is None:
        trainer.callbacks = [adapter]
    else:
        callbacks.append(adapter)
    return adapter
