name: GN3_flows

model:
  model:
    class_path: salt.models.SaltModel
    init_args:

      init_nets:
        - input_name: tracks
          dense_config: &init
            output_size: &embed_dim 256
            hidden_layers: [256]
            activation: &activation SiLU
        - input_name: flow
          dense_config:
            <<: *init

data:
  input_map:
    jets: jets
    tracks: tracks_ghost
    flow: flows
  variables:
    jets:
      - pt_btagJes
      - eta_btagJes
    tracks:
      - d0
      - z0SinTheta
      - dphi
      - deta
      - qOverP
      - IP3D_signed_d0_significance
      - IP3D_signed_z0_significance
      - phiUncertainty
      - thetaUncertainty
      - qOverPUncertainty
      - numberOfPixelHits
      - numberOfSCTHits
      - numberOfInnermostPixelLayerHits
      - numberOfNextToInnermostPixelLayerHits
      - numberOfInnermostPixelLayerSharedHits
      - numberOfInnermostPixelLayerSplitHits
      - numberOfPixelSharedHits
      - numberOfPixelSplitHits
      - numberOfSCTSharedHits
    flow:
      - pt
      - energy
      - deta
      - dphi
      - isCharged
